version: "3"
services:
  nginx:
    image: nginx:${NGINX_VERSION}
    container_name: nginx
    ports:
      - ${NGINX_HTTP_HOST_PORT}:80
      - ${NGINX_HTTPS_HOST_PORT}:443
    volumes:
      - ${WORK_DIR}:/var/www/html
      - $PWD/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - $PWD/nginx/conf/conf.d:/etc/nginx/conf.d
      - $PWD/nginx/logs:/var/log/nginx
    restart: always
    privileged: true
    environment:
      TZ: ${TIMEZONE}
    networks:
      default:
  php56:
    image: registry.cn-hangzhou.aliyuncs.com/balloon/php56
    container_name: php56
    volumes:
      - ${WORK_DIR}:/var/www/html
      - $PWD/php56/conf/php.ini:/usr/local/etc/php/php.ini
      - $PWD/php56/conf/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - $PWD/php56/logs:/var/log/php-fpm
    restart: always
    privileged: true
    environment:
      TZ: ${TIMEZONE}
    networks:
      default:
  php71:
    image: registry.cn-hangzhou.aliyuncs.com/balloon/php71
    container_name: php71
    volumes:
      - ${WORK_DIR}:/var/www/html
      - $PWD/php71/conf/php.ini:/usr/local/etc/php/php.ini
      - $PWD/php71/conf/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - $PWD/php71/logs:/var/log/php-fpm
    extra_hosts:
      - "local.bmtrip.com:172.19.0.2"
      - "local.order.com:172.19.0.2"
      - "steward-local.bmtrip.com:172.19.0.2"
    restart: always
    privileged: true
    environment:
      TZ: ${TIMEZONE}
    networks:
      default:
  php73:
    image: registry.cn-hangzhou.aliyuncs.com/balloon/php73
    container_name: php73
    volumes:
      - ${WORK_DIR}:/var/www/html
      - $PWD/php73/conf/php.ini:/usr/local/etc/php/php.ini
      - $PWD/php73/conf/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini
      - $PWD/php73/conf/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - $PWD/php73/logs:/var/log/php-fpm
    restart: always
    privileged: true
    environment:
      TZ: ${TIMEZONE}
    networks:
      default:
  mysql:
    image: mysql:${MYSQL_VERSION}
    container_name: mysql
    ports:
      - ${MYSQL_HOST_PORT}:3306
    volumes:
      - ${MYSQL_CONF_FILE}:/etc/mysql/conf.d/mysql.cnf
      - ${MYSQL_DATA_DIR}:/var/lib/mysql/
    restart: always
    networks:
      default:
    environment:
      TZ: ${TIMEZONE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  redis:
    image: redis:${REDIS_VERSION}
    container_name: redis
    ports:
      - ${REDIS_HOST_PORT}:6379
    volumes:
      - ${REDIS_CONF_FILE}:/etc/redis.conf
      - ${REDIS_DATA_DIR}:/data
    networks:
      default:
    environment:
      TZ: ${TIMEZONE}
networks:
  default:
    driver: bridge
