FROM php:5.6.31-fpm

RUN apt-get update && apt-get install -y \
        openssl \
        libssl-dev \
        libfreetype6-dev \
        libjpeg62-turbo-dev \
        libpng-dev \
        curl \
        libcurl4-gnutls-dev \
        libmemcached-dev \
        zlib1g-dev \
    && rm -rf /var/lib/apt/lists/*

RUN docker-php-source extract \
    && docker-php-ext-install bcmath pdo_mysql zip \
    && docker-php-source delete

RUN docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
    && docker-php-ext-install -j$(nproc) gd
    
RUN pecl install memcache-2.2.7 \
    && pecl install memcached-2.2.0 \
    && pecl install mongo-1.6.16 \
    && pecl install redis-3.1.5 \
    && pecl install yar-1.2.5 \
    && docker-php-ext-enable memcache memcached mongo redis yar

RUN pecl download yaf-2.3.5 \
    && mkdir -p /tmp/yaf \
    && tar -xf yaf-2.3.5.tgz -C /tmp/yaf --strip-components=1 \
    && rm yaf-2.3.5.tgz \
    && docker-php-ext-configure /tmp/yaf --enable-yaf \
    && docker-php-ext-install /tmp/yaf \
    && rm -r /tmp/yaf

RUN curl -L -o /tmp/tideways.tar.gz "https://github.com/tideways/php-xhprof-extension/archive/v4.1.6.tar.gz" \
    && mkdir tideways \
    && tar -xf /tmp/tideways.tar.gz -C tideways --strip-components=1 \
    && rm /tmp/tideways.tar.gz \
    && ( cd tideways && phpize && ./configure && make -j$(nproc) && make install ) \
    && docker-php-ext-enable tideways \
    && rm -r tideways

RUN curl -sS https://getcomposer.org/installer | \
    php -- --install-dir=/usr/bin/ --filename=composer \
    && composer config -g repo.packagist composer https://mirrors.aliyun.com/composer/